// Total.js translation file
// Created: 2016-10-26 17:50

// views/index.html
T267988893     : This is the content from the view1.

// views/layout.html
T-52966915     : 你好，世界！

// node_modules/total.js/index.js
T39            : '
T-75123236     : TEXT TO TRANSLATE

// node_modules/total.js/internal.js
T662061527     : ', index

// public/plugins/blocky/accessible/libs/angular2-all.umd.min.js
T86899429      : [^:]+